const form = document.getElementById('form');
const mobile = document.getElementById('mobile');
const email = document.getElementById('email');
const city = document.getElementById('city');
const street = document.getElementById('street');
const streetNum = document.getElementById('streetNum');

const citylist2 = [
            "אבו ג'ווייעד (שבט)",
            "אבו גוש",
            "אבו סנאן",
            "אבו סריחאן (שבט)",
            "אבו עבדון (שבט)",
            "אבו עמאר (שבט)",
            "אבו עמרה (שבט)",
            "אבו קורינאת (יישוב)",
            "אבו קורינאת (שבט)",
            "אבו רובייעה (שבט)",
            "אבו רוקייק (שבט)",
            "אבו תלול",
            "אבטין",
            "אבטליון",
            "אביאל",
            "אביבים",
            "אביגדור",
            "אביחיל",
            "אביטל",
            "אביעזר",
            "אבירים",
            "אבן יהודה",
            "אבן מנחם",
            "אבן ספיר",
            "אבן שמואל",
            "אבני איתן",
            "אבני חפץ",
            "אבנת",
            "אבשלום",
            "אדורה",
            "אדירים",
            "אדמית",
            "אדרת",
            "אודים",
            "אודם",
            "אוהד",
            "אום אל-פחם",
            "אום אל-קוטוף",
            "אום בטין",
            "אומן",
            "אומץ",
            "אופקים",
            "אור הגנוז",
            "אור הנר",
            "אור יהודה",
            "אור עקיבא",
            "אורה",
            "אורות",
            "אורטל",
            "אורים",
            "אורנים",
            "אורנית",
            "אושה",
            "אזור",
            "אחווה",
            "אחוזם",
            "אחוזת ברק",
            "אחיהוד",
            "אחיטוב",
            "אחיסמך",
            "אחיעזר",
            "אטרש (שבט)",
            "איבים",
            "אייל",
            "איילת השחר",
            "אילון",
            "אילות",
            "אילנייה",
            "אילת",
            "אירוס",
            "איתמר",
            "איתן",
            "איתנים",
            "אכסאל",
            "אל -עזי",
            "אל -עריאן",
            "אל -רום",
            "אל סייד",
            "אלומה",
            "אלומות",
            "אלון הגליל",
            "אלון מורה",
            "אלון שבות",
            "אלוני אבא",
            "אלוני הבשן",
            "אלוני יצחק",
            "אלונים",
            "אלי-עד",
            "אליאב",
            "אליכין",
            "אליפז",
            "אליפלט",
            "אליקים",
            "אלישיב",
            "אלישמע",
            "אלמגור",
            "אלמוג",
            "אלעד",
            "אלעזר",
            "אלפי מנשה",
            "אלקוש",
            "אלקנה",
            "אמונים",
            "אמירים",
            "אמנון",
            "אמציה",
            "אניעם",
            "אסד (שבט)",
            "אספר",
            "אעבלין",
            "אעצם (שבט)",
            "אפיניש (שבט)",
            "אפיק",
            "אפיקים",
            "אפק",
            "אפרת",
            "ארבל",
            "ארגמן",
            "ארז",
            "אריאל",
            "ארסוף",
            "אשבול",
            "אשבל",
            "אשדוד",
            "אשדות יעקב (איחוד)",
            "אשדות יעקב (מאוחד)",
            "אשחר",
            "אשכולות",
            "אשל הנשיא",
            "אשלים",
            "אשקלון",
            "אשרת",
            "אשתאול",
            "באקה אל-גרביה",
            "באר אורה",
            "באר גנים",
            "באר טוביה",
            "באר יעקב",
            "באר מילכה",
            "באר שבע",
            "בארות יצחק",
            "בארותיים",
            "בארי",
            "בוסתן הגליל",
            "בועיינה-נוג'ידאת",
            "בוקעאתא",
            "בורגתה",
            "בחן",
            "בטחה",
            "ביצרון",
            "ביר אל-מכסור",
            "ביר הדאג'",
            "בירייה",
            "בית אורן",
            "בית אל",
            "בית אלעזרי",
            "בית אלפא",
            "בית אריה",
            "בית ברל",
            "בית ג'ן",
            "בית גוברין",
            "בית גמליאל",
            "בית דגן",
            "בית הגדי",
            "בית הלוי",
            "בית הלל",
            "בית העמק",
            "בית הערבה",
            "בית השיטה",
            "בית זיד",
            "בית זית",
            "בית זרע",
            "בית חורון",
            "בית חירות",
            "בית חלקיה",
            "בית חנן",
            "בית חנניה",
            "בית חשמונאי",
            "בית יהושע",
            "בית יוסף",
            "בית ינאי",
            "בית יצחק-שער חפר",
            "בית לחם הגלילית",
            "בית מאיר",
            "בית נחמיה",
            "בית ניר",
            "בית נקופה",
            "בית עובד",
            "בית עוזיאל",
            "בית עזרא",
            "בית עריף",
            "בית צבי",
            "בית קמה",
            "בית קשת",
            "בית רבן",
            "בית רימון",
            "בית שאן",
            "בית שמש",
            "בית שערים",
            "בית שקמה",
            "ביתן אהרן",
            "ביתר עילית",
            "בלפוריה",
            "בן זכאי",
            "בן עמי",
            "בן שמן (כפר נוער)",
            "בן שמן (מושב)",
            "בני ברק",
            "בני דקלים",
            "בני דרום",
            "בני דרור",
            "בני יהודה",
            "בני נצרים",
            "בני עטרות",
            "בני עי\"ש",
            "בני ציון",
            "בני ראם",
            "בניה",
            "בנימינה-גבעת עדה*",
            "בסמ\"ה",
            "בסמת טבעון",
            "בענה",
            "בצרה",
            "בצת",
            "בקוע",
            "בקעות",
            "בר גיורא",
            "בר יוחאי",
            "ברוכין",
            "ברור חיל",
            "ברוש",
            "ברכה",
            "ברכיה",
            "ברעם",
            "ברק",
            "ברקאי",
            "ברקן",
            "ברקת",
            "בת הדר",
            "בת חן",
            "בת חפר",
            "בת ים",
            "בת עין",
            "בת שלמה",
            "ג'דיידה-מכר",
            "ג'ולס",
            "ג'לג'וליה",
            "ג'נאביב (שבט)",
            "ג'סר א-זרקא",
            "ג'ש (גוש חלב)",
            "ג'ת",
            "גאולי תימן",
            "גאולים",
            "גאליה",
            "גבולות",
            "גבים",
            "גבע",
            "גבע בנימין",
            "גבע כרמל",
            "גבעולים",
            "גבעון החדשה",
            "גבעות בר",
            "גבעת אבני",
            "גבעת אלה",
            "גבעת ברנר",
            "גבעת השלושה",
            "גבעת זאב",
            "גבעת ח\"ן",
            "גבעת חיים (איחוד)",
            "גבעת חיים (מאוחד)",
            "גבעת יואב",
            "גבעת יערים",
            "גבעת ישעיהו",
            "גבעת כ\"ח",
            "גבעת ניל\"י",
            "גבעת עוז",
            "גבעת שמואל",
            "גבעת שמש",
            "גבעת שפירא",
            "גבעתי",
            "גבעתיים",
            "גברעם",
            "גבת",
            "גדות",
            "גדיש",
            "גדעונה",
            "גדרה",
            "גונן",
            "גורן",
            "גורנות הגליל",
            "גזית",
            "גזר",
            "גיאה",
            "גיבתון",
            "גיזו",
            "גילון",
            "גילת",
            "גינוסר",
            "גיניגר",
            "גינתון",
            "גיתה",
            "גיתית",
            "גלאון",
            "גלגל",
            "גליל ים",
            "גלעד (אבן יצחק)",
            "גמזו",
            "גן הדרום",
            "גן השומרון",
            "גן חיים",
            "גן יאשיה",
            "גן יבנה",
            "גן נר",
            "גן שורק",
            "גן שלמה",
            "גן שמואל",
            "גנות",
            "גנות הדר",
            "גני הדר",
            "גני טל",
            "גני יוחנן",
            "גני מודיעין",
            "גני עם",
            "גני תקווה",
            "געש",
            "געתון",
            "גפן",
            "גרופית",
            "גשור",
            "גשר",
            "גשר הזיו",
            "גת (קיבוץ)",
            "גת רימון",
            "דאלית אל-כרמל",
            "דבורה",
            "דבורייה",
            "דבירה",
            "דברת",
            "דגניה א'",
            "דגניה ב'",
            "דוב\"ב",
            "דולב",
            "דור",
            "דורות",
            "דחי",
            "דייר אל-אסד",
            "דייר חנא",
            "דייר ראפאת",
            "דימונה",
            "דישון",
            "דלייה",
            "דלתון",
            "דמיידה",
            "דן",
            "דפנה",
            "דקל",
            "דריג'את",
            "האון",
            "הבונים",
            "הגושרים",
            "הדר עם",
            "הוד השרון",
            "הודיות",
            "הודייה",
            "הוואשלה (שבט)",
            "הוזייל (שבט)",
            "הושעיה",
            "הזורע",
            "הזורעים",
            "החותרים",
            "היוגב",
            "הילה",
            "המעפיל",
            "הסוללים",
            "העוגן",
            "הר אדר",
            "הר גילה",
            "הר עמשא",
            "הראל",
            "הרדוף",
            "הרצלייה",
            "הררית",
            "ורד יריחו",
            "ורדון",
            "זבארגה (שבט)",
            "זבדיאל",
            "זוהר",
            "זיקים",
            "זיתן",
            "זכרון יעקב",
            "זכריה",
            "זמר",
            "זמרת",
            "זנוח",
            "זרועה",
            "זרזיר",
            "זרחיה",
            "ח'ואלד",
            "ח'ואלד (שבט)",
            "חבצלת השרון",
            "חבר",
            "חגור",
            "חגי",
            "חגלה",
            "חד-נס",
            "חדיד",
            "חדרה",
            "חוג'ייראת (ד'הרה) (שבט)",
            "חולדה",
            "חולון",
            "חולית",
            "חולתה",
            "חוסן",
            "חוסנייה",
            "חופית",
            "חוקוק",
            "חורה",
            "חורפיש",
            "חורשים",
            "חזון",
            "חיבת ציון",
            "חיננית",
            "חיפה",
            "חירות",
            "חלוץ",
            "חלץ",
            "חמאם",
            "חמד",
            "חמדיה",
            "חמדת",
            "חמרה",
            "חניאל",
            "חניתה",
            "חנתון",
            "חספין",
            "חפץ חיים",
            "חפצי-בה",
            "חצב",
            "חצבה",
            "חצור הגלילית",
            "חצור-אשדוד",
            "חצרים",
            "חרב לאת",
            "חרוצים",
            "חריש",
            "חרמש",
            "חרשים",
            "חשמונאים",
            "טבריה",
            "טובא-זנגרייה",
            "טורעאן",
            "טייבה",
            "טייבה (בעמק)",
            "טירה",
            "טירת יהודה",
            "טירת כרמל",
            "טירת צבי",
            "טל שחר",
            "טל-אל",
            "טללים",
            "טלמון",
            "טמרה",
            "טמרה (יזרעאל)",
            "טנא",
            "טפחות",
            "יאנוח-ג'ת",
            "יבול",
            "יבנאל",
            "יבנה",
            "יגור",
            "יגל",
            "יד בנימין",
            "יד השמונה",
            "יד חנה",
            "יד מרדכי",
            "יד נתן",
            "יד רמב\"ם",
            "ידידה",
            "יהוד",
            "יהל",
            "יובל",
            "יובלים",
            "יודפת",
            "יונתן",
            "יושיביה",
            "יזרעאל",
            "יחיעם",
            "יטבתה",
            "ייט\"ב",
            "יכיני",
            "ינוב",
            "ינון",
            "יסוד המעלה",
            "יסודות",
            "יסעור",
            "יעד",
            "יעף",
            "יערה",
            "יפיע",
            "יפית",
            "יפעת",
            "יפתח",
            "יצהר",
            "יציץ",
            "יקום",
            "יקיר",
            "יקנעם (מושבה)",
            "יקנעם עילית",
            "יראון",
            "ירדנה",
            "ירוחם",
            "ירושלים",
            "ירחיב",
            "ירכא",
            "ירקונה",
            "ישע",
            "ישעי",
            "ישרש",
            "יתד",
            "כאבול",
            "כאוכב אבו אל-היג'א",
            "כברי",
            "כדורי",
            "כדיתה",
            "כוכב השחר",
            "כוכב יאיר",
            "כוכב יעקב",
            "כוכב מיכאל",
            "כורזים",
            "כחל",
            "כחלה",
            "כיסופים",
            "כישור",
            "כליל",
            "כלנית",
            "כמאנה",
            "כמהין",
            "כמון",
            "כנות",
            "כנף",
            "כנרת (מושבה)",
            "כנרת (קבוצה)",
            "כסיפה",
            "כסלון",
            "כסרא-סמיע",
            "כעביה-טבאש-חג'אג'רה",
            "כפר אביב",
            "כפר אדומים",
            "כפר אוריה",
            "כפר אחים",
            "כפר ביאליק",
            "כפר ביל\"ו",
            "כפר בלום",
            "כפר בן נון",
            "כפר ברא",
            "כפר ברוך",
            "כפר גדעון",
            "כפר גלים",
            "כפר גליקסון",
            "כפר גלעדי",
            "כפר דניאל",
            "כפר האורנים",
            "כפר החורש",
            "כפר המכבי",
            "כפר הנגיד",
            "כפר הנוער הדתי",
            "כפר הנשיא",
            "כפר הס",
            "כפר הרא\"ה",
            "כפר הרי\"ף",
            "כפר ויתקין",
            "כפר ורבורג",
            "כפר ורדים",
            "כפר זוהרים",
            "כפר זיתים",
            "כפר חב\"ד",
            "כפר חושן",
            "כפר חיטים",
            "כפר חיים",
            "כפר חנניה",
            "כפר חסידים א'",
            "כפר חסידים ב'",
            "כפר חרוב",
            "כפר טרומן",
            "כפר יאסיף",
            "כפר ידידיה",
            "כפר יהושע",
            "כפר יונה",
            "כפר יחזקאל",
            "כפר יעבץ",
            "כפר כמא",
            "כפר כנא",
            "כפר מונש",
            "כפר מימון",
            "כפר מל\"ל",
            "כפר מנדא",
            "כפר מנחם",
            "כפר מסריק",
            "כפר מצר",
            "כפר מרדכי",
            "כפר נטר",
            "כפר סאלד",
            "כפר סבא",
            "כפר סילבר",
            "כפר סירקין",
            "כפר עבודה",
            "כפר עזה",
            "כפר עציון",
            "כפר פינס",
            "כפר קאסם",
            "כפר קיש",
            "כפר קרע",
            "כפר ראש הנקרה",
            "כפר רוזנואלד (זרעית)",
            "כפר רופין",
            "כפר רות",
            "כפר שמאי",
            "כפר שמואל",
            "כפר שמריהו",
            "כפר תבור",
            "כפר תפוח",
            "כרכום",
            "כרם בן זמרה",
            "כרם בן שמן",
            "כרם יבנה (ישיבה)",
            "כרם מהר\"ל",
            "כרם שלום",
            "כרמי יוסף",
            "כרמי צור",
            "כרמי קטיף",
            "כרמיאל",
            "כרמייה",
            "כרמים",
            "כרמל",
            "לבון",
            "לביא",
            "לבנים",
            "להב",
            "להבות הבשן",
            "להבות חביבה",
            "להבים",
            "לוד",
            "לוזית",
            "לוחמי הגיטאות",
            "לוטם",
            "לוטן",
            "לימן",
            "לכיש",
            "לפיד",
            "לפידות",
            "לקיה",
            "מאור",
            "מאיר שפיה",
            "מבוא ביתר",
            "מבוא דותן",
            "מבוא חמה",
            "מבוא מודיעים",
            "מבואות ים",
            "מבועים",
            "מבטחים",
            "מבקיעים",
            "מבשרת ציון",
            "מג'ד אל-כרום",
            "מג'דל שמס",
            "מגאר",
            "מגדים",
            "מגדל",
            "מגדל העמק",
            "מגדל עוז",
            "מגדלים",
            "מגידו",
            "מגל",
            "מגן",
            "מגן שאול",
            "מגשימים",
            "מדרך עוז",
            "מדרשת בן גוריון",
            "מדרשת רופין",
            "מודיעין עילית",
            "מודיעין-מכבים-רעות*",
            "מולדת",
            "מוצא עילית",
            "מוקייבלה",
            "מורן",
            "מורשת",
            "מזור",
            "מזכרת בתיה",
            "מזרע",
            "מזרעה",
            "מחולה",
            "מחנה יתיר",
            "מחניים",
            "מחסיה",
            "מטולה",
            "מטע",
            "מי עמי",
            "מיטב",
            "מייסר",
            "מיצר",
            "מירב",
            "מירון",
            "מישר",
            "מיתר",
            "מכורה",
            "מכחול",
            "מכמורת",
            "מכמנים",
            "מלאה",
            "מלילות",
            "מלכייה",
            "מלכישוע",
            "מנוחה",
            "מנוף",
            "מנות",
            "מנחמיה",
            "מנרה",
            "מנשית זבדה",
            "מסד",
            "מסדה",
            "מסילות",
            "מסילת ציון",
            "מסלול",
            "מסעדה",
            "מסעודין אל-עזאזמה (שבט)",
            "מעברות",
            "מעגלים",
            "מעגן",
            "מעגן מיכאל",
            "מעוז חיים",
            "מעון",
            "מעונה",
            "מעיין ברוך",
            "מעיין צבי",
            "מעיליא",
            "מעלה אדומים",
            "מעלה אפרים",
            "מעלה גלבוע",
            "מעלה גמלא",
            "מעלה החמישה",
            "מעלה לבונה",
            "מעלה מכמש",
            "מעלה עירון",
            "מעלה עמוס",
            "מעלה שומרון",
            "מעלות-תרשיחא",
            "מענית",
            "מעש",
            "מפלסים",
            "מצדות יהודה",
            "מצובה",
            "מצליח",
            "מצפה",
            "מצפה אבי\"ב",
            "מצפה אילן",
            "מצפה יריחו",
            "מצפה נטופה",
            "מצפה רמון",
            "מצפה שלם",
            "מצר",
            "מקווה ישראל",
            "מרגליות",
            "מרום גולן",
            "מרחב עם",
            "מרחביה (מושב)",
            "מרחביה (קיבוץ)",
            "מרכז שפירא",
            "משאבי שדה",
            "משגב דב",
            "משגב עם",
            "משהד",
            "משואה",
            "משואות יצחק",
            "משכיות",
            "משמר איילון",
            "משמר דוד",
            "משמר הירדן",
            "משמר הנגב",
            "משמר העמק",
            "משמר השבעה",
            "משמר השרון",
            "משמרות",
            "משמרת",
            "משען",
            "מתן",
            "מתת",
            "מתתיהו",
            "נאות גולן",
            "נאות הכיכר",
            "נאות מרדכי",
            "נאות סמדר",
            "נאעורה",
            "נבטים",
            "נגבה",
            "נגוהות",
            "נהורה",
            "נהלל",
            "נהרייה",
            "נוב",
            "נוגה",
            "נוה צוף",
            "נווה",
            "נווה אבות",
            "נווה אור",
            "נווה אטי\"ב",
            "נווה אילן",
            "נווה איתן",
            "נווה דניאל",
            "נווה זוהר",
            "נווה זיו",
            "נווה חריף",
            "נווה ים",
            "נווה ימין",
            "נווה ירק",
            "נווה מבטח",
            "נווה מיכאל",
            "נווה שלום",
            "נועם",
            "נוף איילון",
            "נופים",
            "נופית",
            "נופך",
            "נוקדים",
            "נורדייה",
            "נורית",
            "נחושה",
            "נחל עוז",
            "נחלה",
            "נחליאל",
            "נחלים",
            "נחם",
            "נחף",
            "נחשולים",
            "נחשון",
            "נחשונים",
            "נטועה",
            "נטור",
            "נטע",
            "נטעים",
            "נטף",
            "ניין",
            "ניל\"י",
            "ניצן",
            "ניצן ב'",
            "ניצנה (קהילת חינוך)",
            "ניצני סיני",
            "ניצני עוז",
            "ניצנים",
            "ניר אליהו",
            "ניר בנים",
            "ניר גלים",
            "ניר דוד (תל עמל)",
            "ניר ח\"ן",
            "ניר יפה",
            "ניר יצחק",
            "ניר ישראל",
            "ניר משה",
            "ניר עוז",
            "ניר עם",
            "ניר עציון",
            "ניר עקיבא",
            "ניר צבי",
            "נירים",
            "נירית",
            "נס הרים",
            "נס עמים",
            "נס ציונה",
            "נעורים",
            "נעלה",
            "נעמ\"ה",
            "נען",
            "נערן",
            "נצאצרה (שבט)",
            "נצר חזני",
            "נצר סרני",
            "נצרת",
            "נצרת עילית",
            "נשר",
            "נתיב הגדוד",
            "נתיב הל\"ה",
            "נתיב העשרה",
            "נתיב השיירה",
            "נתיבות",
            "נתניה",
            "סאג'ור",
            "סאסא",
            "סביון*",
            "סגולה",
            "סואעד (חמרייה)*",
            "סואעד (כמאנה) (שבט)",
            "סולם",
            "סוסיה",
            "סופה",
            "סח'נין",
            "סייד (שבט)",
            "סלמה",
            "סלעית",
            "סמר",
            "סנסנה",
            "סעד",
            "סעוה",
            "סער",
            "ספיר",
            "סתרייה",
            "ע'ג'ר",
            "עבדון",
            "עברון",
            "עגור",
            "עדי",
            "עדנים",
            "עוזה",
            "עוזייר",
            "עולש",
            "עומר",
            "עופר",
            "עוצם",
            "עוקבי (בנו עוקבה) (שבט)",
            "עזוז",
            "עזר",
            "עזריאל",
            "עזריה",
            "עזריקם",
            "עטאוונה (שבט)",
            "עטרת",
            "עידן",
            "עיילבון",
            "עיינות",
            "עילוט",
            "עין איילה",
            "עין אל-אסד",
            "עין גב",
            "עין גדי",
            "עין דור",
            "עין הבשור",
            "עין הוד",
            "עין החורש",
            "עין המפרץ",
            "עין הנצי\"ב",
            "עין העמק",
            "עין השופט",
            "עין השלושה",
            "עין ורד",
            "עין זיוון",
            "עין חוד",
            "עין חרוד (איחוד)",
            "עין חרוד (מאוחד)",
            "עין יהב",
            "עין יעקב",
            "עין כרם-בי\"ס חקלאי",
            "עין כרמל",
            "עין מאהל",
            "עין נקובא",
            "עין עירון",
            "עין צורים",
            "עין קנייא",
            "עין ראפה",
            "עין שמר",
            "עין שריד",
            "עין תמר",
            "עינת",
            "עכו",
            "עלומים",
            "עלי",
            "עלי זהב",
            "עלמה",
            "עלמון",
            "עמוקה",
            "עמיחי",
            "עמינדב",
            "עמיעד",
            "עמיעוז",
            "עמיקם",
            "עמיר",
            "עמנואל",
            "עמקה",
            "ענב",
            "עספיא",
            "עפולה",
            "עפרה",
            "עץ אפרים",
            "עצמון שגב",
            "עראבה",
            "עראמשה*",
            "ערב אל נעים",
            "ערד",
            "ערוגות",
            "ערערה",
            "ערערה-בנגב",
            "עשרת",
            "עתלית",
            "עתניאל",
            "פארן",
            "פדואל",
            "פדויים",
            "פדיה",
            "פוריידיס",
            "פורייה – כפר עבודה",
            "פורייה – נווה עובד",
            "פורייה עילית",
            "פורת",
            "פטיש",
            "פלך",
            "פלמחים",
            "פני חבר",
            "פסגות",
            "פסוטה",
            "פעמי תש\"ז",
            "פצאל",
            "פקיעין (בוקייעה)",
            "פקיעין חדשה",
            "פרדס חנה-כרכור",
            "פרדסייה",
            "פרוד",
            "פרזון",
            "פרי גן",
            "פתח תקווה",
            "פתחיה",
            "צאלים",
            "צביה",
            "צבעון",
            "צובה",
            "צוחר",
            "צופים",
            "צופית",
            "צופר",
            "צוקי ים",
            "צוקים",
            "צור הדסה",
            "צור יצחק",
            "צור משה",
            "צור נתן",
            "צוריאל",
            "צורית",
            "ציפורי",
            "צלפון",
            "צנדלה",
            "צפרייה",
            "צפרירים",
            "צפת",
            "צרופה",
            "צרעה",
            "קבועה (שבט)",
            "קבוצת יבנה",
            "קדומים",
            "קדימה-צורן",
            "קדמת צבי",
            "קדר",
            "קדרון",
            "קדרים",
            "קודייראת א-צאנע (שבט)",
            "קוואעין (שבט)",
            "קוממיות",
            "קורנית",
            "קטורה",
            "קיסריה",
            "קלחים",
            "קליה",
            "קלנסווה",
            "קלע",
            "קציר",
            "קצר א-סר",
            "קצרין",
            "קריית אונו",
            "קריית ארבע",
            "קריית אתא",
            "קריית ביאליק",
            "קריית גת",
            "קריית טבעון",
            "קריית ים",
            "קריית יערים",
            "קריית יערים (מוסד)",
            "קריית מוצקין",
            "קריית מלאכי",
            "קריית נטפים",
            "קריית ענבים",
            "קריית עקרון",
            "קריית שלמה",
            "קריית שמונה",
            "קרני שומרון",
            "קשת",
            "ראמה",
            "ראס אל-עין",
            "ראס עלי",
            "ראש העין",
            "ראש פינה",
            "ראש צורים",
            "ראשון לציון",
            "רבבה",
            "רבדים",
            "רביבים",
            "רביד",
            "רגבה",
            "רגבים",
            "רהט",
            "רווחה",
            "רוויה",
            "רוח מדבר",
            "רוחמה",
            "רומאנה",
            "רומת הייב",
            "רועי",
            "רותם",
            "רחוב",
            "רחובות",
            "רחלים",
            "ריחאנייה",
            "ריחן",
            "ריינה",
            "רימונים",
            "רינתיה",
            "רכסים",
            "רם-און",
            "רמות",
            "רמות השבים",
            "רמות מאיר",
            "רמות מנשה",
            "רמות נפתלי",
            "רמלה",
            "רמת גן",
            "רמת דוד",
            "רמת הכובש",
            "רמת השופט",
            "רמת השרון",
            "רמת יוחנן",
            "רמת ישי",
            "רמת מגשימים",
            "רמת צבי",
            "רמת רזיאל",
            "רמת רחל",
            "רנן",
            "רעים",
            "רעננה",
            "רקפת",
            "רשפון",
            "רשפים",
            "רתמים",
            "שאר ישוב",
            "שבי דרום",
            "שבי ציון",
            "שבי שומרון",
            "שבלי – אום אל-גנם",
            "שגב-שלום",
            "שדה אילן",
            "שדה אליהו",
            "שדה אליעזר",
            "שדה בוקר",
            "שדה דוד",
            "שדה ורבורג",
            "שדה יואב",
            "שדה יעקב",
            "שדה יצחק",
            "שדה משה",
            "שדה נחום",
            "שדה נחמיה",
            "שדה ניצן",
            "שדה עוזיהו",
            "שדה צבי",
            "שדות ים",
            "שדות מיכה",
            "שדי אברהם",
            "שדי חמד",
            "שדי תרומות",
            "שדמה",
            "שדמות דבורה",
            "שדמות מחולה",
            "שדרות",
            "שואבה",
            "שובה",
            "שובל",
            "שוהם",
            "שומרה",
            "שומרייה",
            "שוקדה",
            "שורש",
            "שורשים",
            "שושנת העמקים",
            "שזור",
            "שחר",
            "שחרות",
            "שיבולים",
            "שייח' דנון",
            "שילה",
            "שילת",
            "שכניה",
            "שלווה",
            "שלוחות",
            "שלומי",
            "שלומית",
            "שמיר",
            "שמעה",
            "שמרת",
            "שמשית",
            "שני",
            "שניר",
            "שעב",
            "שעל",
            "שעלבים",
            "שער אפרים",
            "שער הגולן",
            "שער העמקים",
            "שער מנשה",
            "שערי תקווה",
            "שפיים",
            "שפיר",
            "שפר",
            "שפרעם",
            "שקד",
            "שקף",
            "שרונה",
            "שריגים (לי-און)",
            "שריד",
            "שרשרת",
            "שתולה",
            "שתולים",
            "תאשור",
            "תדהר",
            "תובל",
            "תומר",
            "תושייה",
            "תימורים",
            "תירוש",
            "תל אביב -יפו",
            "תל יוסף",
            "תל יצחק",
            "תל מונד",
            "תל עדשים",
            "תל קציר",
            "תל שבע",
            "תל תאומים",
            "תלם",
            "תלמי אליהו",
            "תלמי אלעזר",
            "תלמי ביל\"ו",
            "תלמי יוסף",
            "תלמי יחיאל",
            "תלמי יפה",
            "תלמים",
            "תמרת",
            "תנובות",
            "תעוז",
            "תפרח",
            "תקומה",
            "תקוע",
            "תראבין א-צאנע (שבט)",
            "תרבין א-צאנע (יישוב)*",
            "תרום"
]
const citylist = ["a'sam","abbirim","abu abdun","abu ammar","abu amre","abu ghosh","abu juwei'id","abu qureinat","abu qureinat","abu rubei'a","abu ruqayyeq","abu sinan","abu sureihan","abu tulul","adamit","adanim","adderet","addirim","adi","adora","afeinish","afeq","afiq","afiqim","afula","agur","ahawa","ahi'ezer","ahihud","ahisamakh","ahituv","ahuzzam","ahuzzat baraq","akko","al sayyid","al-aryan","al-azy","ale zahav","alfe menashe","allon hagalil","allon shevut","allone abba","allone abba","allone habashan","allone habashan","allone yizhaq","allonim","alma","almagor","almog","almon","alumim","alumma","alummot","amazya","amazya","amir","amirim","ammi'ad","ammi'oz","ammihay","amminadav","ammiqam","amnun","amqa","amuqqa","ani'am","ar'ara","ar'ara-banegev","arab al naim","arad","aramsha","arbel","argaman","ari'el","arrabe","arsuf","arugot","asad","aseret","asfar","ashalim","ashdod","ashdot ya'aqov(ihud)","ashdot ya'aqov(me'uhad)","asherat","ashqelon","atawne","ateret","atlit","atrash","atsmon segev","avdon","avenat","avi'el","avi'ezer","avigedor","avihayil","avital","avivim","avne etan","avne hefez","avshalom","avtalyon","ayanot","ayyelet hashahar","azarya","azor","azri'el","azriqam","bahan","balfurya","baqa al-gharbiyye","bar giyyora","bar yohay","bar'am","baraq","bareqet","barqan","barqay","basma","basmat tab'un","bat ayin","bat hadar","bat hefer","bat hen","bat shelomo","bat yam","bazra","be'er gannim","be'er milka","be'er ora","be'er sheva","be'er toviyya","be'er ya'aqov","be'eri","be'erot yizhaq","be'erotayim","beit jann","ben ammi","ben shemen (moshav)","ben shemen(k.no'ar)","ben zakkay","benaya","bene atarot","bene ayish","bene beraq","bene darom","bene darom","bene deror","bene deror","bene re'em","bene yehuda","bene ziyyon","beqa'ot","beqoa","berakha","berekhya","beror hayil","berosh","bet alfa","bet arif","bet arye","bet berl","bet dagan","bet el","bet el'azari","bet ezra","bet gamli'el","bet guvrin","bet haarava","bet haemeq","bet hagaddi","bet halewi","bet hanan","bet hananya","bet hashitta","bet hashmonay","bet herut","bet herut","bet hillel","bet hilqiyya","bet horon","bet lehem hagelilit","bet me'ir","bet nehemya","bet neqofa","bet nir","bet oren","bet oved","bet qama","bet qeshet","bet rabban","bet rimmon","bet she'an","bet she'arim","bet shemesh","bet shiqma","bet uzzi'el","bet yannay","bet yehoshua","bet yizhaq-sh. hefer","bet yosef","bet zayit","bet zeid","bet zera","bet zevi","betar illit","bezet","bi'ne","binyamina-giv'at ada","bir el-maksur","bir hadage","biriyya","bitan aharon","bitha","bizzaron","bne deqalim","bne netsarim","brukhin","bu'eine-nujeidat","buq'ata","burgeta","bustan hagalil","daburiyya","dafna","dahi","daliyat al-karmel","daliyya","dalton","dan","daverat","deganya alef","deganya bet","deir al-asad","deir hanna","deir rafat","demeide","deqel","derig'at","devira","devora","dimona","dishon","dolev","dor","dorot","dovev","efrat","eilabun","ein al-asad","ein hod","ein mahel","ein naqquba","ein qiniyye","ein rafa","el-rom","el'ad","el'azar","elat","eli","eli-ad","eliav","elifaz","elifelet","elishama","elon","elon more","elot","elqana","elqosh","elyakhin","elyaqim","elyashiv","emunim","en ayyala","en dor","en gedi","en gev","en habesor","en haemeq","en hahoresh","en hamifraz","en hanaziv","en harod (ihud)","en harod(me'uhad)","en hashelosha","en hashofet","en hod","en iron","en karem-b.s.haqla'i","en karmel","en sarid","en shemer","en tamar","en wered","en ya'aqov","en yahav","en ziwan","en zurim","enat","enav","erez","eshbal","eshbol","eshel hanasi","eshhar","eshkolot","eshta'ol","etan","etanim","even menahem","even sappir","even shemu'el","even yehuda","evron","eyal","ez efrayim","ezer","ezuz","fassuta","fureidis","ga'ash","ga'ton","gadish","gadot","gal'ed (even yizhaq)","gal'on","gan hadarom","gan hashomeron","gan hayyim","gan ner","gan shelomo","gan shemu'el","gan soreq","gan yavne","gan yoshiyya","ganne am","ganne hadar","ganne modi'in","ganne tal","ganne tiqwa","ganne yohanan","gannot","gannot hadar","gat rimmon","gat(qibbuz)","gazit","ge'a","ge'alya","ge'ule teman","ge'ulim","gedera","gefen","gelil yam","gerofit","gesher","gesher haziw","geshur","geva","geva binyamin","geva karmel","geva'ot bar","gevar'am","gevat","gevim","gevulot","gezer","ghajar","gibbeton","gid'ona","gilat","gilgal","gilon","gimzo","ginnaton","ginnegar","ginnosar","gitta","gittit","giv'at avni","giv'at brenner","giv'at ela","giv'at hashelosha","giv'at hayyim (ihud)","giv'at hayyim(me'uhad)","giv'at hen","giv'at koah","giv'at nili","giv'at oz","giv'at shappira","giv'at shemesh","giv'at shemu'el","giv'at ye'arim","giv'at yesha'yahu","giv'at yo'av","giv'at ze'ev","giv'atayim","giv'ati","giv'olim","giv'on hahadasha","gizo","gonen","goren","gornot hagalil","habonim","habonim","had-nes","hadar am","hadera","hadid","hafez hayyim","haggay","hagor","hagosherim","hahoterim","haifa","haluz","hama'pil","hamadya","hamam","hamra","hanita","hannaton","hanni'el","haogen","haon","har adar","har amasa","har gillo","har'el","hararit","harashim","harduf","harish","haruzim","hashmona'im","hasolelim","haspin","havazzelet hasharon","hawashla","hayogev","hazav","hazerim","hazeva","hazon","hazor hagelilit","hazor-ashdod","hazore'im","hazorea","hefzi-bah","helez","hemdat","hemed","herev le'et","hermesh","herut","herzliyya","hever","hibbat ziyyon","hilla","hinnanit","hod hasharon","hodayot","hodiyya","hofit","hogla","holit","holon","horeshim","hosen","hosha'aya","hujeirat (dahra)","hulata","hulda","huqoq","hura","hurfeish","hussniyya","huzayyel","i'billin","ibbim","ibtin","iddan","iksal","ilaniyya","ilut","immanu'el","irus","isifya","itamar","jaljulye","jatt","jerusalem","jish(gush halav)","jisr az-zarqa","judeide-maker","julis","junnabib","ka'abiyye-tabbash-hajajre","kabri","kabul","kaddita","kadoorie","kafar bara","kafar kama","kafar kanna","kafar manda","kafar misr","kafar qara","kafar qasem","kafar yasif","kahal","kallanit","kamane","kammon","kanaf","kannot","kaokab abu al-hija","karkom","karme katif","karme yosef","karme zur","karmel","karmel","karmi'el","karmiyya","kefar adummim","kefar ahim","kefar aviv","kefar avoda","kefar azza","kefar barukh","kefar bialik","kefar bilu","kefar bin nun","kefar blum","kefar daniyyel","kefar daniyyel","kefar ezyon","kefar gallim","kefar gid'on","kefar gil'adi","kefar glikson","kefar habad","kefar hahoresh","kefar hamakkabbi","kefar hanagid","kefar hananya","kefar hanasi","kefar hano'ar hadati","kefar haoranim","kefar harif","kefar haro'e","kefar haruv","kefar hasidim alef","kefar hasidim bet","kefar hayyim","kefar hess","kefar hittim","kefar hittim","kefar hoshen","kefar kisch","kefar malal","kefar masaryk","kefar maymon","kefar menahem","kefar monash","kefar mordekhay","kefar netter","kefar pines","kefar rosh haniqra","kefar rozenwald(zarit)","kefar ruppin","kefar rut","kefar sava","kefar shammay","kefar shemaryahu","kefar shemu'el","kefar silver","kefar sirkin","kefar szold","kefar tappuah","kefar tavor","kefar truman","kefar uriyya","kefar vitkin","kefar warburg","kefar weradim","kefar ya'bez","kefar yedidya","kefar yehezqel","kefar yehoshua","kefar yona","kefar zetim","kefar zoharim","kelil","kemehin","keramim","kerem ben shemen","kerem ben zimra","kerem maharal","kerem shalom","kerem yavne(yeshiva)","kesalon","khawaled","khawaled","kinneret(moshava)","kinneret(qevuza)","kishor","kisra-sumei","kissufim","kochlea","kokhav hashahar","kokhav mikha'el","kokhav ya'aqov","kokhav ya'ir","korazim","kuseife","lahav","lahavot habashan","lahavot haviva","lakhish","lappid","lappidot","laqye","lavi","lavon","lehavim","liman","livnim","lod","lohame hageta'ot","lotan","lotem","luzit","ma'agan","ma'agan mikha'el","ma'ale adummim","ma'ale amos","ma'ale efrayim","ma'ale gamla","ma'ale gilboa","ma'ale hahamisha","ma'ale iron","ma'ale levona","ma'ale mikhmas","ma'ale shomeron","ma'alot-tarshiha","ma'anit","ma'as","ma'barot","ma'galim","ma'on","ma'on","ma'or","ma'oz hayyim","ma'yan barukh","ma'yan zevi","mabbu'im","magen","magen sha'ul","maggal","magshimim","mahanayim","mahane yattir","mahseya","majd al-kurum","majdal shams","makchul","malkishua","malkiyya","manof","manot","manshiyyet zabda","margaliyyot","mas'ade","mas'udin al-'azazme","mash'abbe sade","mash'en","maskiyyot","maslul","massad","massada","massu'a","massu'ot yizhaq","massu'ot yizhaq","matta","mattan","mattat","mattityahu","mattityahu","mavqi'im","mazkeret batya","mazliah","mazor","mazra'a","mazzuva","me ammi","me ammi","me'ir shefeya","me'ona","mefallesim","megadim","megiddo","mehola","meiser","mekhora","mele'a","melilot","menahemya","menara","menuha","merav","merhav am","merhavya(moshav)","merhavya(qibbuz)","merkaz shappira","merom golan","meron","meshar","meshhed","mesillat ziyyon","mesillot","metar","metav","metula","mevasseret ziyyon","mevo betar","mevo betar","mevo dotan","mevo hamma","mevo modi'im","mevo'ot yam","mezadot yehuda","mezadot yehuda","mezar","mezer","mi'elya","midrakh oz","midreshet ben gurion","midreshet ruppin","migdal","migdal haemeq","migdal oz","migdalim","mikhmannim","mikhmoret","miqwe yisra'el","misgav am","misgav dov","mishmar ayyalon","mishmar dawid","mishmar haemeq","mishmar hanegev","mishmar hasharon","mishmar hashiv'a","mishmar hayarden","mishmarot","mishmeret","mitspe ilan","mivtahim","mizpa","mizpe aviv","mizpe netofa","mizpe ramon","mizpe shalem","mizpe yeriho","mizra","modi'in illit","modi'in-makkabbim-re'ut","moledet","moledet","moran","moreshet","moza illit","mughar","muqeible","na'ale","na'ama","na'an","na'aran","na'ura","nahal oz","nahala","nahalal","nahali'el","naham","nahariyya","nahef","nahsholim","nahshon","nahshonim","nasasra","nataf","natur","nave","nazareth","nazerat illit","ne'ot golan","ne'ot hakikkar","ne'ot mordekhay","ne'ot smadar","ne'urim","negba","negohot","nehalim","nehora","nehusha","nein","nes ammim","nes harim","nes ziyyona","nesher","neta","neta'im","netanya","netiv haasara","netiv hagedud","netiv halamed-he","netiv hashayyara","netivot","netu'a","nevatim","neve tsuf","newe ativ","newe avot","newe daniyyel","newe etan","newe harif","newe ilan","newe ilan","newe mikha'el","newe mivtah","newe shalom","newe ur","newe yam","newe yamin","newe yaraq","newe ziv","newe zohar","nezer hazzani","nezer sereni","nili","nir am","nir aqiva","nir banim","nir dawid (tel amal)","nir eliyyahu","nir ezyon","nir ezyon","nir gallim","nir gallim","nir hen","nir moshe","nir oz","nir yafe","nir yisra'el","nir yizhaq","nir zevi","nirim","nirit","nizzan","nizzan b","nizzana (qehilat hinuh)","nizzane oz","nizzane sinay","nizzanim","no'am","nof ayyalon","nofekh","nofim","nofit","nogah","noqedim","nordiyya","nordiyya","nov","nurit","odem","odem","ofaqim","ofer","ofra","ohad","olesh","omen","omer","omez","or aqiva","or haganuz","or haganuz","or haner","or yehuda","ora","oranim","oranit","orot","ortal","otni'el","ozem","pa'ame tashaz","palmahim","paran","pardes hanna-karkur","pardesiyya","parod","pattish","pedaya","pedu'el","peduyim","pelekh","pene hever","peqi'in (buqei'a)","peqi'in hadasha","perazon","peri gan","pesagot","petah tiqwa","petahya","peza'el","porat","poriyya illit","poriyya-kefar avoda","poriyya-newe oved","qabbo'a","qaddarim","qadima-zoran","qalansawe","qalya","qarne shomeron","qasr a-sir","qawa'in","qazir","qazrin","qedar","qedumim","qela","qelahim","qesaryya","qeshet","qeshet","qetura","qevuzat yavne","qidmat zevi","qidron","qiryat anavim","qiryat arba","qiryat atta","qiryat bialik","qiryat eqron","qiryat gat","qiryat mal'akhi","qiryat motzkin","qiryat netafim","qiryat ono","qiryat shelomo","qiryat shemona","qiryat tiv'on","qiryat yam","qiryat ye'arim","qiryat ye'arim(institute)","qomemiyyut","qoranit","qudeirat as-sani","ra'annana","rahat","ram-on","ramat dawid","ramat gan","ramat hakovesh","ramat hasharon","ramat hashofet","ramat magshimim","ramat magshimim","ramat rahel","ramat razi'el","ramat yishay","ramat yohanan","ramat zevi","rame","ramla","ramot","ramot hashavim","ramot me'ir","ramot menashe","ramot naftali","rannen","raqqefet","ras al-ein","ras ali","ravid","re'im","regavim","regba","regba","rehan","rehan","rehelim","rehov","rehovot","reihaniyye","reine","rekhasim","reshafim","retamim","retamim","revadim","revava","revivim","rewaha","rewaya","rimmonim","rinnatya","rishon leziyyon","rishpon","ro'i","rosh haayin","rosh pinna","rosh zurim","rotem","ruah midbar","ruhama","rumat heib","rummane","sa'ad","sa'ar","sa'wa","sajur","sakhnin","sal'it","sallama","samar","sandala","sansana","sappir","sarid","sarigim (li-on)","sasa","savyon","sawa'id (kamane)","sawa'id(hamriyye)","sayyid","sede avraham","sede boqer","sede dawid","sede eli'ezer","sede eliyyahu","sede hemed","sede ilan","sede moshe","sede nahum","sede nehemya","sede nizzan","sede terumot","sede uzziyyahu","sede warburg","sede ya'aqov","sede yizhaq","sede yo'av","sede zevi","sederot","sedot mikha","sedot yam","segev-shalom","segulla","senir","sha'ab","sha'al","sha'alvim","sha'ar efrayim","sha'ar haamaqim","sha'ar hagolan","sha'ar menashe","sha'are tiqwa","shadmot devora","shadmot mehola","shadmot mehola","shafir","shahar","shaharut","shalwa","shamerat","shamir","shani","shaqed","sharona","sharsheret","shave darom","shave shomeron","shave ziyyon","shave ziyyon","she'ar yashuv","shedema","shefar'am","shefayim","shefer","sheikh dannun","shekhanya","shelomi","sheluhot","sheqef","shetula","shetulim","shezor","shibbolim","shibli-umm al-ghanam","shilat","shilo","shim'a","shimshit","shlomit","sho'eva","shoham","shomera","shomeriyya","shoqeda","shorashim","shorashim","shoresh","shoresh","shoshannat haamaqim","shoval","shuva","sitriyya","sufa","sulam","suseya","ta'oz","tal shahar","tal-el","talme bilu","talme el'azar","talme eliyyahu","talme yafe","talme yafe","talme yehi'el","talme yosef","talmon","tamra","tamra (yizre'el)","tarabin as-sani","tarabin as-sani","tarum","tayibe","tayibe(baemeq)","te'ashur","tefahot","tel adashim","tel aviv – yafo","tel mond","tel qazir","tel sheva","tel te'omim","tel yizhaq","tel yosef","telalim","telamim","telem","telem","tene","tenuvot","teqoa","tequma","tiberias","tidhar","tifrah","timmorim","timmorim","timrat","tirat karmel","tirat yehuda","tirat zevi","tire","tirosh","tomer","tuba-zangariyye","tur'an","tushiyya","tuval","udim","umm al-fahm","umm al-qutuf","umm batin","uqbi (banu uqba)","urim","usha","uza","uzeir","wardon","wered yeriho","ya'ad","ya'ara","yad binyamin","yad hanna","yad hashemona","yad hashemona","yad mordekhay","yad natan","yad rambam","yafi","yafit","yagel","yagur","yahel","yakhini","yanuh-jat","yanuv","yaqir","yaqum","yardena","yarhiv","yarqona","yas'ur","yashresh","yated","yavne","yavne'el","yaziz","ye'af","yedida","yehi'am","yehud","yeroham","yesha","yesodot","yesodot","yesud hama'ala","yevul","yif'at","yiftah","yinnon","yir'on","yirka","yish'i","yitav","yitav","yizhar","yizre'el","yodefat","yodefat","yonatan","yonatan","yoqne'am illit","yoqne'am(moshava)","yoshivya","yotvata","yuval","yuvallim","zabarga","zafririm","zafriyya","zanoah","zarzir","zavdi'el","ze'elim","zefat","zekharya","zelafon","zemer","zerahya","zeru'a","zerufa","zetan","zikhron ya'aqov","zimrat","zippori","ziqim","ziv'on","zofar","zofit","zohar","zohar","zor'a","zova","zufim","zuqi yam","zuqim","zur hadassa","zur moshe","zur natan","zur natan","zur yizhaq","zuri'el","zurit","zviyya"];


form.addEventListener('submit', e => {
    var validform = false;
    validform = validateInputs();
    if(validform){
        e.preventDefault();
    }
});

const setError = (element, message) => {
    const inputControl = element.parentElement;
    const errorDisplay = inputControl.querySelector('.error');

    errorDisplay.innerText = message;
    inputControl.classList.add('error');
    inputControl.classList.remove('success');
};

const setSuccess = element => {
    const inputControl = element.parentElement;
    const errorDisplay = inputControl.querySelector('.error');

    errorDisplay.innerText = '';
    inputControl.classList.add('success');
    inputControl.classList.remove('error');
};

const isValidEmail = email => {
    const re = /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    return re.test(String(email).toLowerCase());
};

const isValidMobile = mobile => {
    //const re = /^0?(([23489]{1}\d{7})|[5]{1}\d{8})$/; 
    //return re.test(mobile);
    var phoneNumberPattern = /^[0][5][0|2|3|4|5|9]{1}[-]{0,1}[0-9]{7}$/;

    return phoneNumberPattern.test(mobile);
};

const isValidstreet = street => {
    const regEx1 = /^([a-zA-Z]*)\s+([a-zA-Z ]*)$/; 
    const regEx2 = /[A-Za-z]+\s/;
    if((regEx1.test(String(street).toLowerCase())) || (regEx2.test(String(street).toLowerCase())))
    {
       return true; 
    }
    else{
        return false;
    }
};

function validateInputs(){

    const emailValue = email.value.trim();
    const mobileValue = mobile.value.trim();
    const cityValue = city.value.trim();
    const streetValue = street.value.trim();
    const streetNumValue = streetNum.value.trim();
    var errors = false;


    if(emailValue === '') {
        errors = true;
        setError(email, 'Email is required');
    } else if (!isValidEmail(emailValue)) {
        errors = true;
        setError(email, 'Provide a valid email address');
    } else {
        setSuccess(email);
    }

    if(mobileValue === '') {
        errors = true;
        setError(mobile, 'mobile is required');
    } else if (!isValidMobile(mobileValue) || mobileValue.length != 10) {
        errors = true;
        setError(mobile, 'Provide a valid mobile number.');
    } else {
        setSuccess(mobile);
    }
    
    if(cityValue === '') {
        errors = true;
        setError(city, 'city is required');
    } else if (citylist.indexOf(cityValue.toLowerCase()) == -1 ) {
        errors = true;
        setError(city, 'Provide a valid city name');
    } else {
        setSuccess(city);
    }
    
    if(streetValue === '') {
        errors = true;
        setError(street, 'street is required');
    } else if (!isValidstreet(streetValue) || streetValue.length < 3 || streetValue.length > 20) {
        errors = true;
        setError(street, 'Provide a valid street name');
    } else {
        setSuccess(street);
    }
    
    return errors;

}

